export const openApiSpec = {
  openapi: "3.0.3",
  info: {
    title: "VAGMREACH Commerce API",
    version: "1.0.0",
    description: "Amazon-style REST API for VAGMREACH 1 Gram Gold storefront",
  },
  servers: [{ url: "http://localhost:4000/api/v1" }],
  paths: {
    "/health": { get: { summary: "Health check" } },
    "/products": { get: { summary: "List products" } },
    "/products/{id}": { get: { summary: "Product detail" } },
    "/products/{id}/reviews": { get: { summary: "Product reviews" } },
    "/cart": { get: { summary: "Get cart" }, delete: { summary: "Clear cart" } },
    "/cart/items": { post: { summary: "Add cart item" } },
    "/cart/items/{productId}": {
      patch: { summary: "Update quantity" },
      delete: { summary: "Remove item" },
    },
    "/cart/reserve": { post: { summary: "Reserve stock" } },
    "/cart/reservation": { get: { summary: "Reservation status" } },
    "/cart/reservation/release": { post: { summary: "Release reservation" } },
    "/shipping/pincode/{pin}": { get: { summary: "Resolve pincode" } },
    "/shipping/rates": { get: { summary: "Courier rates" } },
    "/checkout/validate": { post: { summary: "Validate checkout" } },
    "/orders": { post: { summary: "Create order" } },
    "/orders/{orderId}": { get: { summary: "Get order" } },
    "/payments/razorpay/create": { post: { summary: "Create Razorpay order" } },
    "/payments/razorpay/verify": { post: { summary: "Verify Razorpay payment" } },
    "/payments/cod": { post: { summary: "Confirm COD" } },
    "/tracking/{identifier}": { get: { summary: "Track shipment" } },
    "/activity/live": { get: { summary: "Live shoppers" } },
    "/activity/product-view": { post: { summary: "Record product view" } },
    "/auth/register": { post: { summary: "Register customer" } },
    "/auth/login/password": { post: { summary: "Login with password" } },
    "/auth/otp/request": { post: { summary: "Request OTP" } },
    "/auth/otp/verify": { post: { summary: "Verify OTP login" } },
    "/auth/logout": { post: { summary: "Logout" } },
    "/auth/me": { get: { summary: "Current user" }, patch: { summary: "Update profile" } },
    "/me/addresses": { get: { summary: "List addresses" }, post: { summary: "Create address" } },
    "/me/addresses/{id}": { patch: { summary: "Update address" }, delete: { summary: "Delete address" } },
    "/me/orders": { get: { summary: "Order history" } },
    "/admin/products": { get: { summary: "Admin list products" }, post: { summary: "Create product" } },
    "/admin/products/{id}": {
      get: { summary: "Admin get product" },
      patch: { summary: "Update product" },
      delete: { summary: "Soft-delete product" },
    },
    "/admin/orders": { get: { summary: "Admin list orders" } },
    "/admin/orders/{id}": { get: { summary: "Admin order detail" }, patch: { summary: "Update order status" } },
    "/admin/shipments/{id}": { patch: { summary: "Update AWB / tracking" } },
  },
};
